# Generated by Django 5.0.6 on 2024-06-15 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_bio_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'wmv', 'flv'])]),
        ),
    ]
